#ifndef LIGMA_SHARED_INSTRUCTIONS_H
#define LIGMA_SHARED_INSTRUCTIONS_H

#include <shared/definitions.h>

namespace ligma {

const char* BytecodeInstructionShortName (instr_t instruction);
const char* BytecodeInstructionLongName (instr_t instruction);
offset_t BytecodeInstructionLength(instr_t instruction);
    
    
enum bytecode_instruction {
    OPERATION_NOOP,
    OPERATION_PUSH_WORD,
    OPERATION_EXECUTE_WORD,
    OPERATION_PUSH_FLOAT,
    OPERATION_PUSH_INT,
    OPERATION_PUSH_STRING,
    OPERATION_JUMP,
    OPERATION_JUMP_IF_NOT,
    OPERATION_PUSH_LOCAL,
    OPERATION_PUSH_LAMBDA,
    OPERATION_RETURN,
    OPERATION_MAKE_LIST,
    OPERATION_MAKE_VECTOR,
    OPERATION_ALLOCATE_LOCAL,
    OPERATION_DEALLOCATE_LOCAL,
    OPERATION_REPEAT,
    OPERATION_FILE,
    OPERATION_LINE,
    OPERATION_PRINTSTACK,
    OPERATION_PRINTINFO,
    OPERATION_PRINT,
    OPERATION_LISTNEXT,
    OPERATION_LISTDATA,
    OPERATION_LISTNEXTSET,
    OPERATION_LISTDATASET,
    OPERATION_VECTOREXTRACT,
    OPERATION_VECTORINSERT,
    OPERATION_DROP,
    OPERATION_OVER,
    OPERATION_SWAP,
    OPERATION_DUPLICATE,
    OPERATION_ROTATE,
    OPERATION_EQUAL,
    OPERATION_NOTEQUAL,
    OPERATION_GREATERTHAN,
    OPERATION_LESSERTHAN,
    OPERATION_GREATEROREQUAL,
    OPERATION_LESSEROREQUAL,
    OPERATION_AND,
    OPERATION_OR,
    OPERATION_NOT,
    OPERATION_ADD,
    OPERATION_SUB,
    OPERATION_MUL,
    OPERATION_DIV,
    OPERATION_MOD,
    OPERATION_FLOOR,
    OPERATION_ASSIGN,
    OPERATION_LENGTH,
    OPERATION_IDENTITY,
    OPERATION_TYPE,
    OPERATION_CARRIAGE_RETURN,
    OPERATION_EXPLODE
};

}

#endif